version: "3.8"
services:

  db:
    container_name: "postgres"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - backend

  fastapi:
    container_name: "fastapi"
    build: .
    command: uvicorn loader:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/code
    networks:
      - backend

  bot:
    container_name: "bot"
    build:
      dockerfile: ./telegram_bot/Dockerfile
    command: python main.py
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - fastapi
    networks:
      - backend

#cron_run:
#  container_name: "cron_run"
#  build: ./crontab
#  command: cron -n
#  depends_on:
#    - bot
#  networks:
#    - backend

networks:
  backend:
    driver: bridge

volumes:
  db:
    driver: local