version: "3.8"
services:

  db:
    container_name: "postgres"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - backend

  fastapi:
    container_name: "fastapi"
    build: .
    command: uvicorn loader:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/code
    networks:
      - backend

  bot:
    container_name: "bot"
    build:
      dockerfile: ./Dockerfile
    command: python main.py
    restart: always
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - fastapi
    volumes:
      - .:/code
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db:
    driver: local